micronaut:
  server:
    port: 8080
  application:
    name: micronautMeetup

jpa:
  default:
    entity-scan:
      packages:
        - 'micronaut.meetup.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    schema-generate: CREATE_DROP
    driverClassName: org.h2.Driver
meetup:
  hello-world: 'Hello World'
